#!/usr/bin/expect -f

set password [lindex $argv 1]

spawn sudo /usr/bin/passwd [lindex $argv 0]
expect -i $spawn_id "password:"
sleep .5
send "$password\r"
expect "password:"
sleep .5
send "$password\r"
expect eof