#!/usr/bin/expect -f

set password [lindex $argv 0]
set username [lindex $argv 1]
set hostname localhost

spawn /usr/lib/cyrus-imapd/cyradm --user cyrus $hostname
expect "IMAP Password:"
send "$password\r"
expect "$hostname>"
send "sam user.$username cyrus all\r"
expect "$hostname>"
send "dm user.$username\r"
expect "$hostname>"
send "quit\r"
expect eof
