#!/bin/bash

MYEMAIL=`head -n 1 /home/cyrus/$1.vacation`
TEMP=`wc -l /home/cyrus/$1.vacation | fmt -w 1 | tr -d " " | head -n 1`
NUMLINES=$TEMP

if [ $MYEMAIL = $3 ]; then

    touch /home/cyrus/$1.vacation.cache

    if [ `cat /home/cyrus/$1.vacation.cache | grep -c $2` = "0" ]
	then
	`tail -n $NUMLINES /home/cyrus/$1.vacation | /usr/local/bin/sendEmail -f $3 -t $2 -u "Automated Response from $3"
	echo $2 > /home/cyrus/$1.vacation.cache.tmp
	cat /home/cyrus/$1.vacation.cache /home/cyrus/$1.vacation.cache.tmp > /home/cyrus/$1.vacation.cache.tmp2
	mv /home/cyrus/$1.vacation.cache.tmp2 /home/cyrus/$1.vacation.cache
	rm /home/cyrus/$1.vacation.cache.tmp`
    fi
fi

exit 0